# Generated by Django 4.1.2 on 2022-12-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('primerapellido', models.CharField(max_length=30)),
                ('segundoapellido', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(choices=[('Matrona Jefe', 'Matrona Jefe'), ('Matrona General', 'Matrona General')], max_length=20)),
                ('run', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(blank=True, max_length=10, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('primerapellido', models.CharField(max_length=30)),
                ('segundoapellido', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=30)),
                ('primerapellido', models.CharField(max_length=30)),
                ('segundoapellido', models.CharField(blank=True, max_length=30, null=True)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('direccion', models.CharField(max_length=30)),
                ('run', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_alta', models.CharField(blank=True, choices=[('Fallecimiento', 'Fallecimiento'), ('Traslado', 'Traslado'), ('Retorno a Hogar', 'Retorno a Hogar')], max_length=20, null=True)),
                ('fecha_alta', models.DateField(auto_now=True, null=True)),
                ('padres', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.padre')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_diario', models.IntegerField()),
                ('tolerancia_alimentaria', models.CharField(max_length=30)),
                ('orina', models.CharField(max_length=1)),
                ('deposicion', models.CharField(max_length=1)),
                ('sector_sala', models.CharField(choices=[('UTI', 'UTI'), ('UCI', 'UCI')], max_length=3)),
                ('n_cupo', models.CharField(max_length=5)),
                ('fecha', models.DateField(auto_now=True)),
                ('observacion', models.CharField(blank=True, max_length=120, null=True)),
                ('matrona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.matrona')),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reciennacido')),
            ],
        ),
    ]
